config/routes.rb
Rails.application.routes.draw do
  resources :properties do
    resources :rental_requests

  end

  resources :rental_requests do
      member do
        post 'approve'
        post 'deny'
      end
    end

  devise_for :users

  root 'welcome#index'

end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :owner, class_name: 'User', foreign_key: :user_id, primary_key: :id
  has_many :rental_requests

  has_attached_file :profile_pic
  validates_attachment_content_type :profile_pic, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  #for_rent? needs to default to true which means property should be listed unless owner decides to remove it

  #def owner, owner is the one who created the property

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show

    gon.push({
      :lat => @property.latitude.to_f,
      :lng => @property.longitude.to_f
      })


  end



  # GET /properties/new
  def new
    @property = current_user.properties.build
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    address = "#{params[:property][:street_number]}%20#{params[:property][:street_name]}%20#{params[:property][:city]}%20#{params[:property][:state]}%20#{params[:property][:country]}%20#{params[:property][:zip_code]}"
    url = "https://maps.googleapis.com/maps/api/geocode/json?address="+address+"&key=#{ENV['googleapikey']}"

    response = HTTParty.get(url)

    @property = current_user.properties.build(property_params)

    @property.latitude = response['results'][0]['geometry']['location']['lat']
    @property.longitude = response['results'][0]['geometry']['location']['lng']

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    address = "#{params[:property][:street_number]}%20#{params[:property][:street_name]}%20#{params[:property][:city]}%20#{params[:property][:state]}%20#{params[:property][:country]}%20#{params[:property][:zip_code]}"
    url = "https://maps.googleapis.com/maps/api/geocode/json?address="+address+"&key=#{ENV['googleapikey']}"

    response = HTTParty.get(url)

    @property.latitude = response['results'][0]['geometry']['location']['lat']
    @property.longitude = response['results'][0]['geometry']['location']['lng']

    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:description, :country, :profile_pic, :name, :price, :room_type, :street_name, :street_number, :city, :state, :zip_code)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :room_type %><br>
    <%= f.text_field :room_type %>
  </div>
  <div class="field">
    <%= f.label :street_number %><br>
    <%= f.text_field :street_number %>
  </div>
  <div class="field">
    <%= f.label :street_name %><br>
    <%= f.text_field :street_name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :Price_per_Night %><br>
    <%= f.text_field :price, :value => (number_with_precision(f.object.price, :precision => 2) || 0) %>
  </div>
  <div class="field">
    <%= f.label :profile_pic %><br>
    <%= f.file_field :profile_pic %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Properties</h1>

<body>
  <article>

<div class="properties-block">
    <% @properties.each do |property| %>
      <div class="properties_single_box">
      <ul>
        <li class="property_name"><%= property.name %></li>
        <li><%= property.room_type %></li>
        <!-- <td class="datatables"><%#put this in show= property.description %></td> -->
        <li><%= property.country %></li>
        <li><%= property.price %></li>
        <li><%= image_tag(property.profile_pic.url,:size => "200x220")%></li>
        <li><%= link_to 'Show', property %></li>
        <li><%= link_to 'New request', new_property_rental_request_path(property)%></li>
        <% if user_signed_in? && property.user_id == current_user.id %>
        <li><%= link_to 'View all requests', property_rental_requests_path(property) %></li>
        <li><%= link_to 'Edit', edit_property_path(property) %></li>
        <li><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        <% end %>
        <br>
      </ul>
    </div>
    <% end %>

  </article>

<%= render 'shared/mylocation' %>

<%= link_to 'New Property', new_property_path %>

 </body>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @property.description %>
</p>

<p>
  <strong>Country:</strong>
  <%= @property.country %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.street_number + ' ' + @property.street_name + ' ' + @property.city + ' ' + @property.zip_code %>
</p>


<%= render 'shared/googlemap' %>


<% if user_signed_in? && @property.user_id == current_user.id %>
<%= link_to 'Edit', edit_property_path(@property) %> |
<% end %>
<%= link_to 'Back', properties_path %>