config/routes.rb
Rails.application.routes.draw do
  resources :properties do
    resources :rental_requests

  end

  resources :rental_requests do
      member do
        post 'approve'
        post 'deny'
      end
    end

  devise_for :users

  root 'welcome#index'

end

app/models/rental_request.rb
class RentalRequest < ActiveRecord::Base
  belongs_to :user
  belongs_to :property
  default_scope { order({start_date: :desc})} #this will sort(descending) all the requests by their start date


  validate :start_date_before_end_date

  def start_date_before_end_date
    errors.add(:start_date, "cannot precede end date") if end_date && end_date < start_date
  end

  def approve!
   RentalRequest.transaction do
     self.status = "APPROVED"
     self.save!
   end
  end

  def deny!
    RentalRequest.transaction do
      self.status = "DENIED"
      self.save!
    end
  end







end



#
# def approve!
#     if overlapping_approved_requests.empty?
#       CatRentalRequest.transaction do
#         self.status = "APPROVED"
#         self.save!
#         overlapping_pending_requests.each do |request|
#           request.deny!
#         end
#       end
#     else
#       return false
#     end
#   end
#
#   def deny!
#     if self.status == "PENDING"
#       self.status = "DENIED"
#       self.save!
#     end
#   end
#
#   def overlapping_requests
#     CatRentalRequest.where(<<-SQL, self.start_date, self.end_date, self.start_date, self.end_date)
#     ((start_date BETWEEN ? AND ?) OR
#     (end_date BETWEEN ? AND ?))
#     SQL
#   end
#
#   def overlapping_approved_requests
#     if self.id.nil?
#       self.overlapping_requests.where("status = 'APPROVED' AND id IS NOT NULL")
#     else
#       self.overlapping_requests.where("status = 'APPROVED' AND id  <> ?", self.id)
#     end
#   end
#
#   def overlapping_pending_requests
#     if self.id.nil?
#       self.overlapping_requests.where("status = 'PENDING' AND id IS NOT NULL")
#     else
#       self.overlapping_requests.where("status = 'PENDING' AND id  <> ?", self.id)
#     end
#   end
#
#   private
#   def no_overlapping_approved_requests
#     unless self.overlapping_approved_requests.empty? || self.status == 'DENIED' || self.status == 'PENDING'
#       errors[:base] << "Dates can't overlap with other requests"
#     end
#   end
# end
#
#
#






#
#   def approve!
#       CatRentalRequest.transaction do
#         overlapping_requests.where(status: 'PENDING').update_all(status: "DENIED")
#         update! status: 'APPROVED'
#       end
#     end
#
#     def deny!
#       update! status: 'DENIED'
#     end
#
#     def pending?
#       status == 'PENDING'
#     end
#
#     private
#
#     def overlapping_requests
#       CatRentalRequest
#         .where(cat_id: cat_id)
#         .where('start_date BETWEEN :start_date AND :end_date OR
#                 end_date BETWEEN :start_date AND :end_date OR
#                 :start_date BETWEEN start_date AND end_date OR
#                 :end_date BETWEEN start_date AND end_date',
#                 { start_date: start_date, end_date: end_date } )
#         .where.not(id: id)
#     end
#
#     def overlapping_approved_requests
#       overlapping_requests.where(status: 'APPROVED')
#     end
#
#     def doesnt_overlap_existing_approved_request
#       errors.add(:requests, "cannot overlap") if overlapping_approved_requests.any?
#     end
#
#     def start_date_before_end_date
#       errors.add(:start_date, "cannot precede end date") if end_date &&
#                                                             end_date < start_date
#     end
#
#     def set_status
#       self.status ||= "PENDING"
#     end
#

app/controllers/rental_requests_controller.rb
class RentalRequestsController < ApplicationController
  before_action :set_rental_request, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_property, only: [:new, :create, :index]


  # GET /rental_requests
  # GET /rental_requests.json
  def index
    @rental_requests = RentalRequest.all
  end

  # GET /rental_requests/1
  # GET /rental_requests/1.json
  def show
  end

  def approve
   @rental_request = RentalRequest.find(params[:id])
   @rental_request.approve!

   redirect_to property_rental_requests_path(Property.find(@rental_request.property_id)), notice: 'Rental request was Approved.'
  end

  def deny
   @rental_request = RentalRequest.find(params[:id])
   @rental_request.deny!

   redirect_to property_rental_requests_path(Property.find(@rental_request.property_id)), notice: 'Rental request was Denied.'
  end

  # GET /rental_requests/new
  def new
    @rental_request = RentalRequest.new
  end

  # GET /rental_requests/1/edit
  def edit
  end



  # POST /rental_requests
  # POST /rental_requests.json
  def create
    @rental_request = @property.rental_requests.new(rental_request_params)
    @rental_request.user = current_user
    respond_to do |format|
      if @rental_request.save
        format.html { redirect_to @rental_request, notice: 'Rental request was successfully created.' }
        format.json { render :show, status: :created, location: @rental_request }
      else
        format.html { render :new }
        format.json { render json: @rental_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rental_requests/1
  # PATCH/PUT /rental_requests/1.json
  def update
    respond_to do |format|
      if @rental_request.update(rental_request_params)
        format.html { redirect_to @rental_request, notice: 'Rental request was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental_request }
      else
        format.html { render :edit }
        format.json { render json: @rental_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rental_requests/1
  # DELETE /rental_requests/1.json
  def destroy
    @rental_request.destroy
    respond_to do |format|
      format.html { redirect_to rental_requests_url, notice: 'Rental request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental_request
      @rental_request = RentalRequest.find(params[:id])
    end

    def set_property
      @property = Property.find(params[:property_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_request_params
      params.require(:rental_request).permit(:start_date, :end_date)
    end
end



#
#
#
# class CatRentalRequestsController < ApplicationController
#
#
#   def approve
#     @request = CatRentalRequest.find(params[:id])
#     if cats_owner
#       @request.approve!
#     end
#     redirect_to cats_url
#   end
#
#   def deny
#     @request = CatRentalRequest.find(params[:id])
#     if cats_owner
#       @request.deny!
#     end
#     redirect_to cat_url(@request.cat)
#   end
#
#   def index
#     render json: CatRentalRequest.all
#   end
#
#   def show
#     @request = CatRentalRequest.find(params[:id])
#     redirect_to cat_url(@request.cat_id)
#   end
#
#   def new
#     @request = CatRentalRequest.new
#     @cats = Cat.all
#     render :new
#   end
#
#   def create
#     params[:cat_rental_request][:user_id] = current_user.id
#     @request = CatRentalRequest.new(request_params)
#
#     if @request.save
#       redirect_to cat_rental_request_url(@request)
#     else
#       render json: @request.errors
#     end
#   end
#
#   private
#   def request_params
#     params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :user_id)
#   end
#
#   def cats_owner
#     current_user.id == @request.cat.user_id
#   end
# end

app/helpers/rental_requests_helper.rb
module RentalRequestsHelper
end

app/views/rental_requests/_form.html.erb
<%= form_for([@property, @rental_request]) do |f| %>
  <% if @rental_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental_request.errors.count, "error") %> prohibited this rental_request from being saved:</h2>

      <ul>
      <% @rental_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_field :end_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rental_requests/edit.html.erb
<h1>Editing Rental Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @rental_request %> |
<%= link_to 'Back', rental_request_path %>

app/views/rental_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rental Requests</h1>

<table>
  <thead>
    <tr>
      <th class="datatables">Start Date</th>
      <th class="datatables">End Date</th>
      <th class="datatables">Days</th>
      <th class="datatables">Description</th>
      <th class="datatables">User</th>
      <th class="datatables">Status</th>
    </tr>
  </thead>

  <tbody>
    <% @property.rental_requests.each do |rental_request| %>
      <tr>
        <td class="datatables"><%= rental_request.start_date %></td>
        <td class="datatables"><%= rental_request.end_date %></td>
        <td class="datatables"><%= ((rental_request.end_date - rental_request.start_date)/86400).to_i %></td>
        <td class="datatables"><%=Property.find(rental_request.property_id).description %></td>
        <td class="datatables"><%=User.find(rental_request.user_id).email %></td>
        <!-- <td class="datatables"><%= link_to 'Destroy', rental_request, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        <td class="datatables"><%= rental_request.status%></td>
        <% if rental_request.status == "pending" %>
        <td><%= button_to  "Approve", approve_rental_request_url(rental_request), {class: 'btn btn-success'} %></button></td>
        <td><button type="button" class="btn btn-danger btn-sm"><%= link_to 'Deny', deny_rental_request_path(rental_request), method: :deny%></button></button></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <%= link_to 'New Rental request', new_property_rental_request_path %>

app/views/rental_requests/new.html.erb
<h1>New Rental Request</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/rental_requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_rental_request_path(@rental_request) %> |
<%= link_to 'Back', properties_path %>